### ISSUE TITLE
carton check failure lacks details

### ISSUE THREAD

**Issue by jwittkoski** [perl-carton/carton#153]
This failure output from `carton check` doesn't provide helpful information (i.e. human readable version numbers) to the user.

Is this something carton could do or does CPAN::Meta::Requirements have to report this?

    $ carton check
    illegal requirements: minimum above exact specification at /loader/0x19caf88/CPAN/Meta/Requirements.pm line 264
        CPAN::Meta::Requirements::_Range::Exact::with_minimum('CPAN::Meta::Requirements::_Range::Exact=HASH(0x1f52720)', 'version=HASH(0x1fb98c8)') called at /loader/0x19caf88/CPAN/Meta/Requirements.pm line 149
	    CPAN::Meta::Requirements::__modify_entry_for('CPAN::Meta::Requirements=HASH(0x1f63770)', 'ExtUtils::MakeMaker', 'with_minimum', 'version=HASH(0x1fb98c8)') called at /loader/0x19caf88/CPAN/Meta/Requirements.pm line 70
	    CPAN::Meta::Requirements::__ANON__('CPAN::Meta::Requirements=HASH(0x1f63770)', 'ExtUtils::MakeMaker', 'version=HASH(0x1fb98c8)') called at /loader/0x19caf88/CPAN/Meta/Requirements.pm line 88
    	CPAN::Meta::Requirements::add_requirements('CPAN::Meta::Requirements=HASH(0x1f63770)', 'CPAN::Meta::Requirements=HASH(0x1fbe0f8)') called at /loader/0x19caf88/Carton/Tree.pm line 62
    <remaining output removed>

**Comment by miyagawa** [comment]
this should be addressed with https://github.com/miyagawa/cpanminus/pull/446
