### ISSUE TITLE
carton bundle creates bundled carton that doesn't run

### ISSUE THREAD

**Issue by dracos** [perl-carton/carton#171]
Sorry, I'm not sure if this is a carton issue at all, but if not I'm not sure where best to put it. If I run the following on a Debian wheezy server:

```
cd
mkdir carton-test
cd carton-test
curl -O https://raw.github.com/miyagawa/cpanminus/master/cpanm
touch cpanfile
perl cpanm -L local-carton Carton
# [...things install...]
PERL5LIB=~/carton-test/local-carton/lib/perl5 local-carton/bin/carton
# [...empty cpanfile.snapshot is created...]
PERL5LIB=~/carton-test/local-carton/lib/perl5 local-carton/bin/carton bundle
# [...vendor/bin/carton is created...]
perl vendor/bin/carton
```

it all appears to work fine, but at the end I get:

```
File::Spec version 3.4 required--this is only version 3.33 at vendor/bin/carton line 49047.
```

wheezy does indeed have File::Spec 3.33 installed as part of perl-base, but 3.4 was installed by cpanm in `local-carton/lib/perl5/x86_64-linux-gnu-thread-multi/File/Spec.pm` as you would expect - but it's not being included in the packed carton.

I saw 658541b4ad74686a22f834dd8ade4e2482907d78 but I wasn't sure if that was relevant to this; I can't see a PathTools .packlist which would be why it's not included but I'm not sure precisely of the purpose of that file or when it would or would not be created.

**Comment by miyagawa** [comment]
with v1.0.20 the fatpack carton is optional, and a separate command.
