### ISSUE TITLE
Carton install without running tests

### ISSUE THREAD

**Issue by kidambisrinivas** [perl-carton/carton#190]
Hi, Thanks for the great tool Carton. I'm interested to know how to make 

`carton install`

run fast for a large number of dependencies. I tried setting the environment variable PERL_CPANM_OPT to "-n" to avoid tests. But cpanm seems much faster and carton still installs the dependencies slowly. Could you help me make "Carton install" run faster for 100s of dependencies in production where I dont want to run tests.

**Comment by miyagawa** [comment]
carton install doesn't run tests by itself. If you see slowness in building then that should be something else.
