### ISSUE TITLE
Carton::Mirror->new() got an odd number of elements at

### ISSUE THREAD

**Issue by cono** [perl-carton/carton#192]
Looks like after migration to Class::Tiny, issue appeared:

carton install dies with:
Carton::Mirror->new() got an odd number of elements at /usr/lib64/perl5/vendor_perl/5.20.2/Carton/CLI.pm line 69

This helped:
```
diff CLI.pm /usr/lib64/perl5/vendor_perl/5.20.2/Carton/CLI.pm 
30c30
<     Carton::Mirror->new($ENV{PERL_CARTON_MIRROR} || $Carton::Mirror::DefaultMirror);
---
>     Carton::Mirror->new(url => $ENV{PERL_CARTON_MIRROR} || $Carton::Mirror::DefaultMirror);
219c219
<         $builder->mirror(Carton::Mirror->new($env->vendor_cache));
---
>         $builder->mirror(Carton::Mirror->new(url => $env->vendor_cache));
```

```
diff Builder.pm /usr/lib64/perl5/vendor_perl/5.20.2/Carton/Builder.pm 
20c20
<     push @mirrors, Carton::Mirror->new('http://backpan.perl.org/');
---
>     push @mirrors, Carton::Mirror->new(url => 'http://backpan.perl.org/');
```

**Comment by cono** [comment]
Carton
Latest version installed: 1.0.15

**Comment by miyagawa** [comment]
@cono I cannot reproduce the error. Which version of Class::Tiny do you have?

**Comment by miyagawa** [comment]
Class::Tiny 1.001 is required in cpanfile and META, so as long as you have the version correctly introduced there shouldn't be an issue.

**Comment by cono** [comment]
@miyagawa sorry, looks like something wrong with g-cpan util (gentoo linux), it installed Class:Tiny as a dependency, but the wrong version.

# perl -MClass::Tiny -le 'print $Class::Tiny::VERSION'
1.000

Sorry again.
