### ISSUE TITLE
feature: allow customizing --cache directory

### ISSUE THREAD

**Issue by karenetheridge** [perl-carton/carton#194]
I'm transitioning from an in-house-built package management system, and the tarballs are stored in a different directory. It would be extremely convenient to be able to specify this directory instead of having it be fixed to `vendor/cache`.

**Comment by miyagawa** [comment]
Well, allowing users to change the directory is one legit requirement, while allowing to reuse the tarballs generated by other software might not be.

**Comment by miyagawa** [comment]
Am I right to assume what you actually want is to set `PERL_CARTON_MIRROR` to `file://path/to/cache` and not use the vendor bundle feature - since they're not really relevant?

**Comment by karenetheridge** [comment]
I didn't know about that variable. Maybe it will do what I want!
