### ISSUE TITLE
carton for Synology package ?

### ISSUE THREAD

**Issue by empierre** [perl-carton/carton#201]
Hello,

I plan to make a synology package but the barebone perl and multiple processors structure needs meto understand what and how to do it.

I wanted to go with Dancer2 for it is pure perl, but I still need plack and starman.

I can setup a toolchain for many processors on an intel machine, but I don't have any guarantee this will be the same perl except for a facial version. 

Also there is no compiler by default on the target machines by default.

  Can I achieve my objectives with Carton ? Any help is welcome !

**Comment by miyagawa** [comment]
starman is in XS and you need a C compiler. Carton _could_ be fatpacked but I usually don't recommend it, instead I recommend you to take a look at making a cross build using `cpanm -L local`, then copy the files.
