### ISSUE TITLE
Carton fails with mixed versions of ExtUtils::MakeMaker

### ISSUE THREAD

**Issue by melo** [perl-carton/carton#211]
Note: This is not a Carton bug, but it can cause Carton failures. I'm not sure if there is anything we can do here though...

If the version of ExtUtils::MakeMaker on the workstation where `carton install` was run to generate the `cpanfile.snapshot` is more recent than the version on the server where `carton install --deployment` is run, Carton can fail with missing dependencies warnings.

I got this problem with perl-5.20.3.

To reproduce:

* install two copies of perl-5.20.3, called "workstation" and "server": if you have perlbrew, two lib's is enough;
* on the "workstation" version, upgrade `ExtUtils::MakeMaker`: perl-5.20.3 uses 6.98, my updated version is 7.20;
* use a `cpanfile` with a single line: `requires 'JSON::MaybeXS';`. This module includes a "recommends" section. You should be able to reproduce the issue with any module that has a "recommends" section;
* generate the `cpanfile.snapshot` on the "workstation" perl;
* run `carton install --deployment` on the "server" perl.

---

I'm not sure what `Carton` could do to "solve" this issue. I guess we could add a `ExtUtils::MakeMaker` dependency on `Carton` itself to force it to a more recent version, not sure if there is some other solution more correct.

For now, what I did was forcing the upgrade of `ExtUtils:MakeMaker` on all servers where I install `Carton`.

**Comment by miyagawa** [comment]
what is it that requires the new ExtUtils::MakeMaker? There was a problem in old version of Module::Install before, that it tries to require whatever you have in local.

[Carmel](http://github.com/miyagawa/Carmel) doesn't have this kind of problem by the way.

**Comment by melo** [comment]
On 6.98, when you run `perl Makefile.PL` of `JSON::MaybeXS`, the _recommended_ `Cpanel::JSON::XS` is added as a _required dependency_. On 7.20, that doesn't happen anymore.

Basically, if you install `JSON::MaybeXS` with a 6.98, `Cpanel::JSON::XS` will always be installed, with 7.20 it will not.

When you create the `cpanfile.snapshot` using 7.20, it will not reference the `Cpanel::JSON::XS` dist because, correctly, it is not a required dependency, just a recomendation, and it was not installed.

But when you install on the server, using 6.98, it becomes a required dependency, and given that `--deployment` was used, and it is not mentioned on `02packages.details.txt`, it fails to install.

I checked the ChangeLog of ExtUtils::MakeMaker but there is no mention of this change (at least no mention of "recommends" change).

I also checked the relevant code:

* 6.98: https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-6.98/lib/ExtUtils/MakeMaker.pm#L493 (references a _all_prereqs() that is just a hash merge - https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-6.98/lib/ExtUtils/MM_Any.pm#L2702);
* 7.20: https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.20/lib/ExtUtils/MakeMaker.pm#L558;

The code was substancially re-written, and more, I consider the 7.20 version correct, so there is no point on opening a bug on `ExtUtils::MakeMaker`.

Again, I don't think this is a bug on Carton. My main intent was to raise the issue so that people could find this later, unless you have some suggestion on how to make this work better.

Regarding Carmel, I'll read more about it, specially http://weblog.bulknews.net/post/116798134354/carmel, to understand it better. Are you using it already, in production? I think I understand how it works but I'll need to try it out. It seems to me that it will keep the cached artifacts in the repository, but maybe I'm reading the docs wrong. If that is true, then XS modules would be a problem because my "build" is a MacOS laptop, and the server is Linux.

But it would solve this issue, because you don't install nothing on the server. Carmel is more Docker-esque, the dependencies are installed before-hand, and included in the deployment.

**Comment by miyagawa** [comment]
Ahh, sudden promotion of recommends to requires. Understood. Thanks for the explanation!

**Comment by miyagawa** [comment]
> Are you using it already, in production?

I use it in cpanmetadb production, yes. I tried to apply it to one of my work app that is using Carton right now, but never have got around to it.

> I think I understand how it works but I'll need to try it out. It seems to me that it will keep the cached artifacts in the repository, but maybe I'm reading the docs wrong. 

That is correct, but it's a per-host cache to speed up the installation, but also separated per perl version + arch.

> If that is true, then XS modules would be a problem because my "build" is a MacOS laptop, and the server is Linux.

That should not be an issue because it's separated per architecture. Actually, the recommended workflow is:

- you'll continue building and managing your dependencies in Mac, and commit to your git
- run the install on a CI/staging server with the same architecture with your production
- rsync, add to docker, or build a package, whatever - to deploy to the production

**Comment by melo** [comment]
Thanks for the workflow. I'll try it when I switch over to a Docker-based workflow.

One thing that I like is that the local `$HOME/.carmel/` is shared between projects, that would reduce disk space usage compared to the Carton per-project `local/` and speed up installation. It is a really cool design.

Regarding this issue with `ExtUtils::MakeMaker`, as I said, I don't consider this a bug with Carton, just an heads-up in case someone is bitten by this. I can close the ticket if you prefer.

**Comment by melo** [comment]
Upgrading `ExtUtils::MakeMaker` still gave me sporadic errors. Turns out this is module installation order dependent.

From the `JSON::MaybeXS` [Makefile.PL](https://metacpan.org/source/ETHER/JSON-MaybeXS-1.003005/Makefile.PL#L81):

    # we require Cpanel::JSON::XS, except if JSON::XS is already installed.
    # (we also always recommend Cpanel::JSON::XS, just to make sure.)

The code checks to see if it can load `JSON::XS`, and it not, them bumps `Cpanel:JSON::XS`. This means that if on one of your servers `JSON::XS` is not installed before `JSON::MaybeXS`, it will fail.

The easiest way out seems to be just requiring `Cpanel::JSON::XS` directly.

Thanks for your time.

**Comment by miyagawa** [comment]
Yea, those dynamic dependencies based on what modules are already installed would always cause issues like this.
