### ISSUE TITLE
Trying to use JSON::XS in a docker container fails

### ISSUE THREAD

**Issue by pccowboy** [perl-carton/carton#215]
I have created a project in carton that installs into a Docker container.  However, one module is reported as not present, even when I manually attach to the container and install it.

The build host and the container host are the same machine.  This host has the Perl core packages installed.

Is this possibly because JSON::XS depends on some C library that is not being carried over?  This was my first thought, but the commandline tool json_xs appears to work in the container.  local/liblperl/JSON.pm is definitely present

Here is a log of my docker session, where I use both cpanm and carton to try and get JON::XS to be installed and found:
```
[dswift@0ff275d0-37c9-4cb3-8c27-c9373f3d4b50 perl]$ docker run -i -t --entrypoint /bin/bash zettit/rss_reader    [15/1965]
root@f6532b1fdb6d:/perl# carton exec ./rss_feeds_mgr.pl -c pccowboy_rss_reader_config.json
Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /perl/local/lib/perl5 /etc/p
erl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/sha
re/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at ./rss_feeds_mgr.pl line 1
5.
BEGIN failed--compilation aborted at ./rss_feeds_mgr.pl line 15.
root@f6532b1fdb6d:/perl# cpanm JSON::XS
--> Working on JSON::XS
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-3.02.tar.gz ... OK
==> Found dependencies: Canary::Stability
--> Working on Canary::Stability
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2012.tar.gz ... OK
Configuring Canary-Stability-2012 ... OK
Building and testing Canary-Stability-2012 ... OK
Successfully installed Canary-Stability-2012
Configuring JSON-XS-3.02 ... OK
==> Found dependencies: Types::Serialiser, common::sense
--> Working on Types::Serialiser
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.0.tar.gz ... OK
Configuring Types-Serialiser-1.0 ... OK
==> Found dependencies: common::sense
--> Working on common::sense
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.74.tar.gz ... OK
Configuring common-sense-3.74 ... OK
Building and testing common-sense-3.74 ... OK
Successfully installed common-sense-3.74
Building and testing Types-Serialiser-1.0 ... OK
Successfully installed Types-Serialiser-1.0
Building and testing JSON-XS-3.02 ... OK
Successfully installed JSON-XS-3.02
4 distributions installed
root@f6532b1fdb6d:/perl# carton exec ./rss_feeds_mgr.pl -c pccowboy_rss_reader_config.json
Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /perl/local/lib/perl5 /etc/p
erl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/sha
re/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at ./rss_feeds_mgr.pl line 1
5.
BEGIN failed--compilation aborted at ./rss_feeds_mgr.pl line 15.
root@f6532b1fdb6d:/perl# carton update
HTTP::Request::Common is up to date. (6.11)
Crypt::OpenSSL::RSA is up to date. (0.28)
File::Slurp is up to date. (9999.19)
XML::RSS::Timing is up to date. (1.07)
Date::Format is up to date. (2.24)
Net::Statsd is up to date. (0.12)
DBI is up to date. (1.636)
common::sense is up to date. (3.74)
Sys::SigAction is up to date. (0.23)
Types::Serialiser is up to date. (1.0)
Digest::HMAC is up to date. (1.03)
POE::Component::Client::HTTP is up to date. (0.949)
XML::RSS::Feed is up to date. (2.4)
XML::Parser is up to date. (2.44)
Config::JSON is up to date. (1.5202)
Canary::Stability is up to date. (2012)
Digest::SHA1 is up to date. (2.13)
LWP::UserAgent is up to date. (6.15)
POE::Component::RSSAggregator is up to date. (1.11)
XML::RSS is up to date. (1.59)
POE is up to date. (1.367)
JSON::XS is up to date. (3.02)
root@f6532b1fdb6d:/perl# carton exec ./rss_feeds_mgr.pl -c pccowboy_rss_reader_config.json
Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /perl/local/lib/perl5 /etc/p
erl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/sha
re/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at ./rss_feeds_mgr.pl line 1
5.
BEGIN failed--compilation aborted at ./rss_feeds_mgr.pl line 15.
root@f6532b1fdb6d:/perl# json_
json_pp  json_xs
root@f6532b1fdb6d:/perl# json_xs -version
^C
root@f6532b1fdb6d:/perl# json_xs --help
Unknown option: help
Usage: /usr/local/bin/json_xs [-v] -f fromformat [-e code] [-t toformat]
```

**Comment by melo** [comment]
Hi,

trying to figure out what is going on.

First: do you have JSON::XS on your `cpanfile`? And did you run `carton install` to update the `cpanfile.snapshot` file?

That is usually what bites me.

Second, I'm guessing that `carton exec` might be using a different perl executable than the cpanm that you used to install JSON::XS... That would explain what you are seeing.

This base image uses the official Perl docker image, and if I remember correctly (can't check at the moment, only tonight) it does not replace the system perl.

I'm pretty sure it works fine with JSON::XS, I use this image on projects that depend on that module, but I'll try a minimalist cpanfile with just JSON::XS when I get home to make sure there is nothing broken that I might have missed.

Thanks,

**Comment by pccowboy** [comment]
Hi, thanks for the quick response.

My dev cycle looks like this:
1.  In my local dir, I run 'carton install'
2.  I add and commit the cpanfile and cpanfile.snapshot, and push them into git.
3.  a Jenkins job runs to create the docker image.  This job tars up the project (including cpanfile*) and dumps it into the container under /perl
4.  In the Dockerfile, I use 'FROM perl:latest' and have a line 'RUN cd /perl && carton install' to install the modules locally.
5.  I can see the line "Successfully installed JSON-XS-3.02" in the Jenkins console output

All that said, I did not realise the 'perl:latest' image would have a different executable than system, so I can try and work my way through resolving that, and also see what your testing looks like once you have a chance.  If you have any more pointers, very happy for the help!

**Comment by melo** [comment]
I'll check it later. I did a quick peek on a project and I actually use a base image I built, https://github.com/melo/docker-perl-carton-base, that is based on perl:latest but takes care of all the carton details for me... Maybe I'm doing something there that makes this all work.

One thing that I do differently, is that I prefer to split the login into three steps:

    COPY cpanfile cpanfile.snapshot /perl
    RUN cd /perl && carton install --deployment
    COPY . /perl

The big advantage is that you only do the carton install part if either of cpanfile or cpanfile.snapshot changes between docker builds. If not, follow up builds reuse your dependencies layer, making for a much faster build process.

I'll check tonight, but I definitively use JSON::XS and Carton without problems.

**Comment by pccowboy** [comment]
Ah, I think I see, looks like I need to use an image with 5.16.3 64-bit from something like https://github.com/Perl/docker-perl and get that running for this project

**Comment by melo** [comment]
See this: https://gist.github.com/melo/9b148de1772f1ddee52df9ebe76aa4c1

You can clone it locally and run `./build.sh` to test it.

I tried to keep as close to your dev cycle as I could. it is a simple perl project, with cpanfile for deps, uses a tarball to send code to the container (although I would recommend the setup I use on the docker-perl-carton-base project above, it is more efficient), and everything.

No problems at all with docker Perl latest + carton.

I recommend this issue to be closed.

**Comment by pccowboy** [comment]
Pedro,  thank you for going above and beyond, I really appreciate your help and guidance.

I will indeed convert to the setup you mentioned, as I had been wondering how I should get my project to not rebuild every container during my development.

Thanks again,
David
