### ISSUE TITLE
Feature: Option to only generate cpanfile.snapshot

### ISSUE THREAD

**Issue by ath88** [perl-carton/carton#221]
I would like to have an option to only generate a snapshot-file without actually installing all the modules in `./local`.

**Comment by miyagawa** [comment]
This is implemented in [Carmel](/miyagawa/Carmel).

**Comment by ath88** [comment]
Gorgeous! Thank you! :)

**Comment by mavit** [comment]
How does one do that in Carmel?  I couldn't find an option.

**Comment by miyagawa** [comment]
@mavit if you create a cpanfile, then run `carmel install` - it will manage the modules under your home directory (`~/.carmel`) and only generate `cpanfile.snapshot` under your project directory, like stated in this issue.
