### ISSUE TITLE
Releasing (current changes from) 1.1 branch?

### ISSUE THREAD

**Issue by heikojansen** [perl-carton/carton#235]
Is there any chance you'll publish the changes currently present in the 1.1 branch either as a 1.1 release (with other possibly planned features postponed to 1.x or 1.1.x) or as new 1.0.x?
Being able to deploy our own internally created modules via vendor/cache (or maybe internal git) instead of having to set up a DarkPAN / CPAN mirror for that would save us some time and resources.
Or would this better be requested as a feature for Carmel?

**Comment by miyagawa** [comment]
are you specifically looking to use the `dist` option in cpanfile? The `git` option in cpanfile is kinda flawed and i would rather not support, but maybe `dist` can be used stably. 1.1 branch is behind the current 1.0 branch so we need to do some merge work.

And yes, my primary focus is around Carmel and make it feature parity with Carton to direct all the future work towards carmel. (or even make Carmel a Carton 2.0)

**Comment by heikojansen** [comment]
The ```dist``` option seems more interesting to us (and probably less error prone in real world use).

As far as we understand it, the feature relies on the requirements ```options``` already supported by the currently released ```Module::CPANFile``` so there should be no dependency problems. There are only nine commits in the 1.1 branch and not all of them are related to this feature so creating a patch for it should not be too difficult.

I you want we can try to prepare a pull request. Would you rather rebase the 1.1 branch and have the ```git``` part removed again to then release a version 1.1?
Or would you prefer to "backport" the ```dist``` option to master?

**Comment by miyagawa** [comment]
I added the feature in cpanm/Menlo, which means Carton will likely get it for free. https://github.com/miyagawa/cpanminus/pull/568

**Comment by heikojansen** [comment]
A colleague of mine tested the ```dist``` option with the latest DEV release of ```App::cpanminus``` and apparently it works for our use case. Thank you!

**Comment by heikojansen** [comment]
In the end I was wrong: Things still did not work as we wanted them to. So for the sake of future reference I wanted to describe the workaround we found (plus a possible issue we see):

To re-phrase our intention: we want to install packages created in-house and not released to CPAN without having to run our own DarkPAN. We thought we could use the ```dist``` option in our cpanfile to point to some .tar.gz archive and have Carton install that. Apparently that's not how it works.

The workaround we found utilizes the fact that the contents of ```cpanfile``` are considered Perl code:
```perl
my $dist_archive = 'file://' . $ENV{'PWD'} . '/vendor/dist/';
requires 'My::Own::Mod', url => $dist_archive . 'My-Own-Mod-0.001.tar.gz';
```

Now ```carton install``` picks up the archive file and happily installs the module from it.
(We're using Carton v1.0.30 and App::cpanminus v1.7907 DEV)

However, after successfully finishing ```carton install``` the module is *not* referenced in ```cpanfile.snapshot```. 
Nevertheless, on running ```carton install --deployment``` for new application instances the local modules *are* installed - apparently, even with ```--deployment``` the ```cpanfile``` is still analyzed?!

So right now our use case is covered but we're not exactly sure if that is by design or by accident...

**Comment by miyagawa** [comment]
> To re-phrase our intention: we want to install packages created in-house and not released to CPAN without having to run our own DarkPAN. We thought we could use the dist option in our cpanfile to point to some .tar.gz archive and have Carton install that

Yes, that's the intent and if it does not work it's a bug or at least a design mistake. (Carton has a lot of bugs and mistakes and that's why I'm building Carmel from scratch but that's another story)

> Now carton install picks up the archive file and happily installs the module from it.

Can you describe what you did before and why it's not working?

> Nevertheless, on running carton install --deployment for new application instances the local modules are installed - apparently, even with --deployment the cpanfile is still analyzed?!

That's normal, since you still need to examine `cpanfile` to figure out what needs to be installed. `--deployment` is merely a flag to "do not look for CPAN mirrors when the dependencies can not be satisfied."

**Comment by heikojansen** [comment]
As far as I remember we simply tried lines like this in ```cpanfile```:

```perl
requires "My::Own::Mod" => ">= 0.001", dist => "vendor/dist/My-Own-Mod-0.001.tar.gz";
```
or

```perl
requires "My::Own::Mod" => ">= 0.001", dist => "./vendor/dist/My-Own-Mod-0.001.tar.gz";
```

(The archive being a dependency of the current project and therefore stored in a subdirectory relative to the ```cpanfile``` and thus also to the directory in which ```carton``` was executed.)

But Carton (or cpanm?) kept trying to find a dist on the CPAN mirror, like
```Fetching http://cpan.metacpan.org/authors/id////vendor/dist/My-Own-Mod-0.001.tar.gz ... FAIL```

Executing ```cpanm -L local vendor/dist/My-Own-Mod-0.001.tar.gz``` worked just fine.

**Comment by miyagawa** [comment]
please read the discussion here https://github.com/miyagawa/cpanminus/pull/568 and Carton documentation https://metacpan.org/pod/Carton#Specifying-a-CPAN-distribution

`dist` does not support arbitrary URL or file path. You have to specify the PAUSE-style `author/dist` path in there. Alternatively you can use `url` where you can specify a full URL, including file:// URL.

**Comment by heikojansen** [comment]
Well, yes, that's exactly what we found out as I described in my second-to-last comment. 
But as I said there (and also in the first comment) we did not want to publish our internal modules in an in-house DarkPAN mirror so that Carton + ```dist``` + ( ```PERL_CARTON_MIRROR``` or ```mirror``` ) could find them.

That's just why we came up with the ```url```-based solution described above. The main problem to overcome was that one cannot use relative```file://``` URLs.

We have now verified that while our ```url```-referenced local modules do *not* show up in the ```cpanfile.snapshot``` their dependencies *are* listed in there.
And you wrote that consulting the ```cpanfile``` for modules to install is expected behavior.
Together that means we no longer have to worry this could silently change so our use case is covered *and* reliably so.

The root cause for our misunderstanding was probably that we thought ```dist``` would take a somewhat arbitrary value because that's what you can pass to ```cpanm``` on the command line.

**Comment by miyagawa** [comment]
> The main problem to overcome was that one cannot use relativefile:// URLs.

I tried `file://./foo/bar/...` and it seems to work for me.

**Comment by heikojansen** [comment]
I'm sure it didn't work for us but I'll try again tomorrow...

**Comment by miyagawa** [comment]
OK, `file:./foo` seems to work, while `file://./foo` does not.

**Comment by heikojansen** [comment]
Had no luck here, no matter if using ```file:./```, ```file:```, ```file://./``` or ```file://``` (each with relative paths).

    --> Working on Log::Log4perl
    Fetching file:./vendor/dist/Log-Log4perl-1.49.tar.gz ... FAIL

    --> Working on YYY
    Fetching file:vendor/dist/YYY-0.001001.tar.gz ... FAIL

    --> Working on Mojolicious::Plugin::AssetPack::Pipe::PostCSS
    Fetching file://./vendor/dist/Mojolicious-Plugin-AssetPack-Pipe-PostCSS-0.001001.tar.gz ... FAIL

    --> Working on XXX
    Fetching file://vendor/dist/XXX-0.005001.tar.gz ... FAIL

In the end, ```Log::Log4perl``` ended up being installed but that was the CPAN version indirectly required by another dependency:

    ==> Found dependencies: Log::Log4perl::Layout, Log::Log4perl, Log::Log4perl::MDC, Log::Log4perl::Level, Test::Compile, Log::Log4perl::Layout::PatternLayout
    Searching Log::Log4perl::Layout on mirror index /digibib/p2/portal/local/cache/modules/02packages.details.txt ...
    Searching Log::Log4perl::Layout (0) on cpanmetadb ...
    --> Working on Log::Log4perl::Layout
    Fetching http://cpan.metacpan.org/authors/id/M/MS/MSCHILLI/Log-Log4perl-1.49.tar.gz ... OK

I have no idea why it works for you.
Versions in use here still are carton v1.0.30 and cpanm 1.7907 (though ```cpanm -v``` tells me it's "cpanm (App::cpanminus) 1.9019 on perl 5.024001 built for x86_64-linux").

**Comment by heikojansen** [comment]
By the way: If I understand https://tools.ietf.org/html/rfc8089 correctly, relative paths in file:// URIs are unsupported. So even if that works for you somehow it probably shouldn't ;-)
