### ISSUE TITLE
Maybe new Carton broke MetaCPAN Travis install?

### ISSUE THREAD

**Issue by oalders** [perl-carton/carton#236]
At the very least, there are some warnings from `Menlo`, which were not there before:  https://travis-ci.org/metacpan/metacpan-web/jobs/369557091

There's nothing in this branch which should cause module installs to start failing.  Let me know if I can provide any more info.

**Comment by skaji** [comment]
@oalders I’ve just released cpm 0.969 to CPAN. This issue should be fixed.

**Comment by oalders** [comment]
Thanks @skaji. That fixed it. :)

**Comment by skaji** [comment]
@oalders Sorry for inconvenience, and thank you for your patience!
