### ISSUE TITLE
Can't locate List::MoreUtils in @INC

### ISSUE THREAD

**Issue by srchulo** [perl-carton/carton#250]
I'm running `carton install` and see this error:

```
Installing modules using /home/user/app/cpanfile
! Parsing /home/user/app/cpanfile failed: Can't locate List::MoreUtils in @INC (@INC contains: /home/user/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/x86_64-linux /home/user/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0 /home/user/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.0/x86_64-linux /home/admin/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.0) at /home/user/app/cpanfile line 22.
! Configuring /home/user/app/ failed. See /home/user/.cpanm/work/1551662071.25431/build.log for details.
Installing modules failed
```

The thing is I can confirm that List::MoreUtils is in `/home/user/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0`, and `List::MoreUtils::XS` is in `/home/user/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/x86_64-linux`

For some reason, this is the only module that fails. If I comment these two out, then `carton install` works. Here is how they look in my `cpanfile`:

``
require 'List::MoreUtils';
require 'List::MoreUtils::XS'; 
``

**Comment by skaji** [comment]
You probably want to use `requires`, not `require` :)

**Comment by srchulo** [comment]
Ugghh, I am so sorry about that. Thanks for spell checking me :)
