### ISSUE TITLE
Missing Carton dependency Menlo-CLI-Compat-1.901800

### ISSUE THREAD

**Issue by god-of-hellfire** [perl-carton/carton#264]
Latest release of Carton v1.0.34 references to the dependency Menlo-CLI-Compat that is not longer available in the version 1.901800 on metacpan.org.

**Comment by miyagawa** [comment]
Menlo::CLI::Compat is part of Menlo-Legacy distro and is still available.
https://metacpan.org/release/Menlo-Legacy

**Comment by god-of-hellfire** [comment]
In course of digging into metacpan's api I had run this query at https://explorer.metacpan.org
* endpoint: `/v1/release/_search`
* query: 
```
{
  "query" : { "match_all" : {} },
    "filter" : {
      "and"  : [
        { "term" : { "distribution" : "Carton" } },
        { "term" : { "version_numified" : 1.000034 } }    
      ]    
    }  
}
```
The dependency array contains this entry with the non-accessible version of the module `Menlo::CLI::Compat` respectively its parent release `Menlo-Legacy`:
```
{
  "version" : "1.9018",
   "module" : "Menlo::CLI::Compat",
   "relationship" : "requires",
   "phase" : "runtime"
}
```
I have been stumbled about it because I need to deeply resolve this dependencies. Maybe the CPAN shells like cpanplus will ignore this and try to use the latest version. But this is not feasible for me.

**Comment by miyagawa** [comment]
version in a dependency (derived by META.json) follows the CPAN::Meta::Spec specification https://metacpan.org/pod/CPAN::Meta::Spec#Version-Ranges where it defines "1.9018" as "1.9018 or later".

If you're trying to resolve "1.9018" as exactly 1.9018, you're resolving it incorrectly.
