### ISSUE TITLE
perlbrew + carton: Do not hardcode version in shebang

### ISSUE THREAD

**Issue by KES777** [perl-carton/carton#271]
I use perlbrew to host perl.

I use carton to manage project's modules.

When I switch to new perl and try to reinstall modules I found that they are not rebuild.

Finally I found that everything inside `local/bin` hardcode perl version:
```$cat bin/carton
#!/home/kes/perl5/perlbrew/perls/perl-5.24.1/bin/perl
use strict;
use 5.008001;
use Carton::CLI;

exit Carton::CLI->new->run(@ARGV);

__END__
```

Here we can see that this script do nothing specific to perl 5.24.1. Why version is hardcoded?

Please do not hardcode perl version for scripts in shebang

**Comment by miyagawa** [comment]
shebang rewriting is done by the installers (MakeMaker, Module::Build etc). I recommend you to not check in Carton into the cpanfile deps and instead install to your perlbrew host.

In general, `local` directory has to be nuked and rebuilt with the snapshot when you change your perl version.
