### ISSUE TITLE
cpanfile.snapshot is not created

### ISSUE THREAD

**Issue by KES777** [perl-carton/carton#272]
If installation failed the `cpanfile.snapshot is not created:
```
carton
Installing modules using /home/kes/work/projects/tucha/monkeyman/cpanfile
! Installing Devel::Declare failed. See /home/kes/.cpanm/work/1592838673.26132/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Installed version (0.006022) of Devel::Declare is not in range '== 0.006019'
! Bailing out the installation for /home/kes/work/projects/tucha/monkeyman/.
Installing modules failed
```
[build.log](https://github.com/perl-carton/carton/files/4814070/build.log)
Thus I can not find which module requires `Devel::Declare is not in range '== 0.006019'` dependency

```
Checking if you have Devel::Declare == 0.006019 ... No (0.006022 doesn't satisfy == 0.006019)

```

Expected behavior: cpanfile.snapshot shold be always created. Probably in case of error with slightly different extention: `cpanfile.snapshot_part`

**Comment by miyagawa** [comment]
> Thus I can not find which module requires Devel::Declare is not in range '== 0.006019' dependency

That's not what this error message says. It's trying to install 0.006019, which is pinned in your cpanfile, and was failing.

**Comment by KES777** [comment]
No. That is not in my cpan file. I do not require Devel::Declare directly. From the log I can not understand which module requires it.

Currently I run `carton` under debugger and modify its source so it creates `cpanfile.snapshot`. 

From there I can find:
```
  Method-Signatures-20170211
    pathname: B/BA/BAREFOOT/Method-Signatures-20170211.tar.gz
    provides:
      Method::Signatures 20170211
      Method::Signatures::Modifiers 20170211
      Method::Signatures::Parameter undef
      Method::Signatures::Signature undef
      Method::Signatures::Types undef
      Method::Signatures::Utils undef
    requirements:
      Any::Moose 0.11
      Const::Fast 0.006
      Devel::Declare 0.006002
      Devel::Declare::MethodInstaller::Simple 0.006002
      Lexical::SealRequireHints 0.008
```

I even do not require directly `Method-Signatures` from my `cpanfile`

So here I asking that it would be nice if `carton` creates `cpanfile.snapshot` despite on success or fail

**Comment by miyagawa** [comment]
the build.log you linked has a line that says 
```
Configuring /home/kes/work/projects/tucha/monkeyman
...
Checking if you have Devel::Declare == 0.006019 ... No (0.006022 doesn't satisfy == 0.006019)
```
which means you have the exact requirement for that in `cpanfile`, or in META.yml or other means.

**Comment by n-insaidoo** [comment]
Is there a special option at this point in time that allows to achieve what is being asked by the PR author?
@KES777 have you managed to produce the expected behaviour alternatively, hence having a `cpanfile.snapshot_part` generated somehow?

**Comment by KES777** [comment]
@n-insaidoo No, I have not.
