### ISSUE TITLE
Parsing module version of Getopt::Long 2.55

### ISSUE THREAD

**Issue by robrwo** [perl-carton/carton#288]
Getopt::Long 2.55 adds a new module to the distribution, that defines the version like so
```perl
use Getopt::Long (); our $VERSION = $Getopt::Long::VERSION;
```
The problem is that Carton uses a different version of Getopt::Long (loaded as a prereq of Carton) so it sets the version incorrectly in `cpanfile.snapshot`:
```diff
-  Getopt-Long-2.54
-    pathname: J/JV/JV/Getopt-Long-2.54.tar.gz
+  Getopt-Long-2.55
+    pathname: J/JV/JV/Getopt-Long-2.55.tar.gz
     provides:
-      Getopt::Long 2.54
-      Getopt::Long::CallBack 2.54
-      Getopt::Long::Parser 2.54
+      Getopt::Long 2.55
+      Getopt::Long::CallBack 2.55
+      Getopt::Long::Parser 2.52
```

I image this issue will affect any prerequisite of Carton that is being changed in the local library.

Note that I've reported this as an [issue with Getopt::Long]( https://github.com/sciurius/perl-Getopt-Long/issues/21), since it makes it difficult to determine the version by tools that have a different version of it loaded in memory.

**Comment by miyagawa** [comment]
PAUSE failed to parse the version as well so that module is not indexed with the correct distribution either.

```
➜  curl -s http://www.cpan.org/modules/02packages.details.txt.gz | gzcat | grep Getopt-Long-2 
Getopt::Long                       2.55  J/JV/JV/Getopt-Long-2.55.tar.gz
Getopt::Long::CallBack             2.55  J/JV/JV/Getopt-Long-2.55.tar.gz
Getopt::Long::Parser               2.54  J/JV/JV/Getopt-Long-2.54.tar.gz
```

This should be fixed in the distribution.
